name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --dart-define=SUPABASE_URL=https://dipgysgcwtrvvkyvybmk.supabase.co/ --dart-define=SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpcGd5c2djd3RydnZreXZ5Ym1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3NDE2MDksImV4cCI6MjEwMzMxNzYwOX0.xpJVcGFeSq0Zc_hU5PH0TgDehBmL6tzV5yjwBwwKpO4 --dart-define=CLOUDINARY_CLOUD_NAME=hnunt5cn --dart-define=CLOUDINARY_UPLOAD_PRESET=gurudarshan

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GuruDarshan-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk
